### ISSUE TITLE
Using Slugworth prevents creation of new ActiveRecord Objects

### ISSUE THREAD

**Issue by dmastylo** [mattpolito/slugworth#9]
```
Booking.create()
```

undefined method `parameterize' for nil:NilClass

Doesn't matter if there are parameters included or not.

**Comment by avogel3** [comment]
I realize this is an old thread, but it looks like this was fixed with the release of 1.2.1 ([CHANGELOG](https://github.com/mattpolito/slugworth/blob/master/CHANGELOG.md))
